name: Build Packer AMI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2.0.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.7
      with:
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Verify AWS credentials
      run: aws sts get-caller-identity

    - name: Initialize Packer Plugins
      run: packer init template.pkr.hcl

    - name: Validate Packer template
      run: packer validate template.pkr.hcl  
    
    - name: Build AMI
      run: packer build template.pkr.hcl


